import {
  BarChart3,
  Bell,
  Brain,
  Building2,
  CloudRain,
  FileSearch,
  FileText,
  GraduationCap,
  Home,
  Layers,
  Leaf,
  LineChart,
  Network,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Sprout,
  TrendingUp,
  User,
  Users,
  Wallet,
  Store,
  Phone,
} from "lucide-react";
import type { NavItem } from "@/components/dashboard/DashShell";

export const FARMER_NAV: NavItem[] = [
  { to: "/farmer", label: "Overview", icon: Home },
  { to: "/farmer/intake", label: "Intake Form", icon: User },
  { to: "/farmer/records", label: "Record Updates", icon: FileText },
  { to: "/farmer/ussd", label: "USSD Access", icon: Phone },
  { to: "/farmer/profile", label: "My Profile", icon: User },
  { to: "/farmer/farm", label: "Farm Profile", icon: Sprout },
  { to: "/farmer/trust-score", label: "Trust Score", icon: ShieldCheck },
  { to: "/farmer/credit", label: "Credit Readiness", icon: TrendingUp },
  { to: "/farmer/loans", label: "Loan Applications", icon: Wallet },
  { to: "/farmer/marketplace", label: "Data Marketplace", icon: Store },
  { to: "/farmer/assistant", label: "AI Assistant", icon: Sparkles },
  { to: "/farmer/climate", label: "Climate Intelligence", icon: CloudRain },
  { to: "/farmer/analytics", label: "Farm Analytics", icon: BarChart3 },
  { to: "/farmer/cooperative", label: "Cooperative", icon: Users },
  { to: "/farmer/network", label: "Relationship Network", icon: Network },
  { to: "/farmer/reports", label: "Reports", icon: FileText },
  { to: "/farmer/notifications", label: "Notifications", icon: Bell },
  { to: "/farmer/settings", label: "Settings", icon: Settings },
];

export const LENDER_NAV: NavItem[] = [
  { to: "/lender", label: "Overview", icon: Home },
  { to: "/lender/farmers", label: "Farmer Directory", icon: Users },
  { to: "/lender/applications", label: "Loan Applications", icon: Layers },
  { to: "/lender/trust", label: "Trust Scores", icon: ShieldCheck },
  { to: "/lender/graph", label: "Graph Intelligence", icon: Network },
  { to: "/lender/climate", label: "Climate Intelligence", icon: CloudRain },
  { to: "/lender/explainability", label: "Explainable AI", icon: Brain },
  { to: "/lender/portfolio", label: "Portfolio Analytics", icon: LineChart },
  { to: "/lender/risk", label: "Risk Management", icon: ShieldAlert },
  { to: "/lender/reports", label: "Reports", icon: FileText },
  { to: "/lender/assistant", label: "AI Assistant", icon: Sparkles },
  { to: "/lender/settings", label: "Institution Settings", icon: Building2 },
  { to: "/lender/notifications", label: "Notifications", icon: Bell },
];

// Keep referenced icons in tree-shake graph
export const _icons = { FileSearch, Leaf, GraduationCap };
